const KEY='rambutanLapangan.v1';
const phases=[
  {from:1,to:30,name:'Adaptasi',target:'Tanaman tidak layu berkepanjangan, drainase baik, daun mayoritas hijau.'},
  {from:31,to:90,name:'Pemulihan & pertumbuhan awal',target:'Tunas mulai tumbuh, akar semakin mapan, dan gulma terkendali.'},
  {from:91,to:180,name:'Pembentukan tajuk',target:'Tajuk bertambah, daun sehat, dan respons nutrisi dapat diamati.'},
  {from:181,to:270,name:'Penguatan tanaman',target:'Pertumbuhan stabil dan tidak ada serangan hama berat.'},
  {from:271,to:365,name:'Persiapan tahun kedua',target:'12 pohon sehat dan kebutuhan tahun kedua ditentukan dari data.'}
];
const nutrients=[
  [22,30,'Kompos awal ±0,5 kg bila tanaman stabil.'],[39,45,'NPK I ±10 g sekali, jangan menempel batang.'],[60,66,'Kompos II ±0,5–1 kg; pastikan tanah tidak tergenang.'],[75,81,'NPK II ±10–15 g bila daun dan tunas sehat.'],[120,126,'Kompos III ±1 kg; bersihkan gulma lebih dahulu.'],[147,153,'NPK III ±15–20 g; catat respons tanaman.'],[207,213,'Kompos IV ±1 kg; jaga jarak dari batang.'],[234,240,'NPK IV ±20 g bila sehat; kurangi jika tanaman kecil.'],[270,276,'Kompos V ±1 kg; pantau pembungaan.'],[327,333,'NPK V ±20–25 g hanya untuk tanaman sehat.']
];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const defaultState={startDate:'2026-08-28',checks:{},trees:{}};
let state=load(), selectedDay=1, scheduleFilter='semua';
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function dateAt(day){const d=new Date(state.startDate+'T12:00:00');d.setDate(d.getDate()+day-1);return d}
function fmt(d,long=false){return new Intl.DateTimeFormat('id-ID',long?{weekday:'long',day:'numeric',month:'long',year:'numeric'}:{day:'numeric',month:'short',year:'numeric'}).format(d)}
function todayDay(){return Math.max(1,Math.min(365,Math.floor((new Date().setHours(12,0,0,0)-new Date(state.startDate+'T12:00:00'))/86400000)+1))}
function phaseFor(day){return phases.find(p=>day>=p.from&&day<=p.to)||phases[4]}
function focusFor(day){const n=nutrients.find(x=>day>=x[0]&&day<=x[1]);if(n)return n[2];if(day>=178&&day<=181)return 'Evaluasi tengah tahun: ukur kondisi dan catat perubahan.';if(day<=21)return 'Cek air, daun, adaptasi; tanpa NPK.';return 'Cek air, gulma, daun, hama, bunga/buah.'}
function schedule(){return Array.from({length:122},(_,i)=>{const day=1+i*3;return{day,date:dateAt(day),focus:focusFor(day),done:!!state.checks[day]}})}
function statusFor(tree){const t=state.trees[tree];if(!t)return{label:'Belum diperiksa',cls:'warn'};if(t.leaf==='Layu'||t.pest==='Berat'||t.soil==='Becek')return{label:'Perlu perhatian',cls:'warn'};return{label:'Baik',cls:'good'}}
function groupFor(n){return String.fromCharCode(65+Math.floor((n-1)/3))}
function scoreRecord(t={}){let score=88;const risks=[],advice=[];if(t.soil==='Kering'){score-=14;risks.push('kekurangan air');advice.push('Periksa kelembapan dan siram bila tanah memang kering.')}if(t.soil==='Becek'){score-=20;risks.push('kelebihan air');advice.push('Hentikan penyiraman sementara dan periksa drainase.')}if(t.leaf==='Pucat'){score-=15;risks.push('daun pucat');advice.push('Amati nutrisi, akar, dan perubahan warna daun.')}if(t.leaf==='Layu'){score-=27;risks.push('daun layu');advice.push('Periksa air, akar, dan naungan; jangan memupuk saat stres.')}if(t.shoot==='Ada')score+=4;if(t.shoot==='Tidak'){score-=5;risks.push('belum ada tunas baru')}if(t.flower==='Bertambah')score+=2;if(t.flower==='Rontok'){score-=6;risks.push('bunga rontok')}if(t.fruit==='Bertambah')score+=3;if(t.fruit==='Rontok'){score-=9;risks.push('buah rontok')}if(t.pest==='Ringan'){score-=13;risks.push('hama/penyakit ringan');advice.push('Periksa bagian terserang dan dokumentasikan penyebarannya.')}if(t.pest==='Berat'){score-=31;risks.push('hama/penyakit berat');advice.push('Pisahkan sumber serangan dan minta pemeriksaan penyuluh pertanian.')}if(t.weed==='Ringan')score-=4;if(t.weed==='Padat'){score-=11;risks.push('gulma padat');advice.push('Bersihkan gulma tanpa melukai akar atau batang.')}const fields=['soil','leaf','shoot','flower','fruit','pest','weed'],complete=fields.filter(k=>t[k]).length;return{score:Math.max(0,Math.min(100,Math.round(score))),complete,risks,advice}}
function treeHistory(tree){return Object.entries(state.checks).map(([day,trees])=>({day:+day,data:trees[tree]})).filter(x=>x.data).sort((a,b)=>a.day-b.day)}
function aiAnalyze(tree){const current=state.trees[tree];if(!current)return{score:null,confidence:0,label:'Belum ada data',risk:'Isi pemeriksaan',advice:'Lengkapi tujuh indikator lapangan.',trend:'belum tersedia'};const base=scoreRecord(current),history=treeHistory(tree),oldHistory=history.slice(0,-1),previous=oldHistory.slice(-3).map(x=>scoreRecord(x.data).score),prior=previous.length?previous.reduce((a,b)=>a+b,0)/previous.length:null,delta=prior===null?0:base.score-prior,measurements=['heightCm','stemCm','moisturePct'].filter(k=>Number.isFinite(current[k])).length,confidence=Math.min(95,Math.round(base.complete/7*65+measurements*5+Math.min(history.length,5)*4));let label=base.score>=85?'Sehat':base.score>=70?'Cukup sehat':base.score>=50?'Perlu perhatian':'Risiko tinggi';let risk=base.risks.length?base.risks.slice(0,2).join(', '):'tidak ada risiko utama';let trend=prior===null?'data awal':delta>=5?'membaik':delta<=-5?'menurun':'stabil';const oldMeasured=[...oldHistory].reverse().find(x=>Number.isFinite(x.data.heightCm)||Number.isFinite(x.data.stemCm));if(oldMeasured&&((Number.isFinite(current.heightCm)&&current.heightCm>oldMeasured.data.heightCm)||(Number.isFinite(current.stemCm)&&current.stemCm>oldMeasured.data.stemCm)))trend=trend==='menurun'?'campuran':'bertumbuh';return{score:base.score,confidence,label,risk,trend,advice:base.advice[0]||'Pertahankan pemeriksaan rutin dan catat setiap perubahan.'}}
function renderAI(){const analyses=Array.from({length:12},(_,i)=>aiAnalyze(i+1)),known=analyses.filter(x=>x.score!==null),avg=known.length?Math.round(known.reduce((a,b)=>a+b.score,0)/known.length):null;$('#aiGardenScore').textContent=avg===null?'—':avg+'%';$('#aiGardenLabel').textContent=avg===null?'Menunggu data pemeriksaan':avg>=85?'Kondisi kebun sehat':avg>=70?'Kondisi kebun cukup sehat':avg>=50?'Kebun perlu perhatian':'Risiko kebun tinggi';const urgent=analyses.filter(x=>x.score!==null&&x.score<70).length;$('#aiGardenAdvice').textContent=avg===null?'Isi pemeriksaan setiap pohon agar sistem dapat menghitung skor dan risiko.':urgent?`${urgent} pohon perlu ditinjau. Prioritaskan skor terendah dan indikator berisiko.`:'Lanjutkan pemeriksaan berkala untuk memperkuat tren dan keyakinan model.';$('#aiTreeGrid').innerHTML=analyses.map((a,i)=>`<button class="ai-tree" data-tree="${i+1}"><div class="ai-tree-head"><h3>Pohon ${i+1} · ${groupFor(i+1)}</h3><span class="ai-percent">${a.score===null?'—':a.score+'%'}</span></div><div class="ai-meter"><span class="${a.score!==null&&a.score<50?'low':a.score!==null&&a.score<70?'medium':''}" style="width:${a.score||0}%"></span></div><p>${a.label} · tren ${a.trend}</p><span class="ai-confidence">Keyakinan data ${a.confidence}%</span><div class="ai-detail">${a.score===null?a.advice:`Risiko: ${a.risk}. ${a.advice}`}</div></button>`).join('')}
function renderHome(){const day=todayDay(),p=phaseFor(day),items=schedule(),done=items.filter(x=>x.done).length, attention=Object.keys(state.trees).filter(n=>statusFor(n).cls==='warn').length;$('#dateLabel').textContent=fmt(new Date(),true).toUpperCase();$('#dayTitle').textContent=`Hari ke-${day}`;$('#progressPct').textContent=Math.round(day/365*100)+'%';$('#phaseLabel').textContent=p.name;$('#todayFocus').textContent=focusFor(day);$('#todayAdvice').textContent=day<=21?'Fokus pada air dan akar. Jangan memaksa bunga atau buah.':'Catat kondisi sebelum melakukan tindakan agar perubahan mudah dibandingkan.';$('#doneCount').textContent=done;$('#attentionCount').textContent=attention;$('#treePreview').innerHTML=[1,2,3,4].map(n=>`<button class="tree-mini" data-tree="${n}"><span>♧</span><strong>Pohon ${n}</strong><small>${statusFor(n).label}</small></button>`).join('');const next=items.find(x=>x.day>=day&&!x.done)||items.find(x=>!x.done);$('#nextTitle').textContent=next?`Hari ke-${next.day} · ${next.focus}`:'Semua jadwal selesai';$('#nextDate').textContent=next?fmt(next.date,true):'365 hari tuntas';}
function renderSchedule(){const now=todayDay();let items=schedule();if(scheduleFilter==='belum')items=items.filter(x=>!x.done);if(scheduleFilter==='selesai')items=items.filter(x=>x.done);$('#scheduleList').innerHTML=items.map(x=>`<button class="schedule-item ${x.done?'done':''} ${x.day<now?'overdue':''}" data-day="${x.day}"><span class="schedule-day"><strong>${x.day}</strong><small>HARI</small></span><span><h3>${x.focus}</h3><p>${fmt(x.date)} · ${phaseFor(x.day).name}</p></span><i class="status-dot"></i></button>`).join('')||'<p class="hint">Tidak ada jadwal pada kategori ini.</p>'}
function renderTrees(){ $('#treeGrid').innerHTML=Array.from({length:12},(_,i)=>i+1).map(n=>{const t=state.trees[n],s=statusFor(n),a=aiAnalyze(n);return `<button class="tree-card" data-tree="${n}"><div class="tree-card-top"><span class="tree-avatar">♧</span><span class="group-badge">Kelompok ${groupFor(n)}</span></div><h3>Pohon ${n}</h3><p>${t?'Terakhir: '+fmt(new Date(t.savedAt)):'Belum ada catatan'}</p><div class="tree-ai"><div class="tree-ai-bar"><i style="width:${a.score||0}%"></i></div><strong>${a.score===null?'—':a.score+'%'}</strong></div><div class="condition"><span>AI: ${a.label}</span><strong class="${s.cls}">${s.label}</strong></div></button>`}).join('')}
function renderReport(){const items=schedule(),done=items.filter(x=>x.done).length,pct=Math.round(done/items.length*100);$('#reportPct').textContent=pct+'%';$('#reportSummary').textContent=done?`${done} dari ${items.length} jadwal telah dicatat.`:'Belum ada pemeriksaan tersimpan.';renderAI();const vals=Object.values(state.trees);const indicators=[['Daun sehat',vals.filter(x=>x.leaf==='Hijau').length],['Tanah baik',vals.filter(x=>x.soil==='Lembap').length],['Ada tunas',vals.filter(x=>x.shoot==='Ada').length],['Ada bunga',vals.filter(x=>x.flower==='Ada'||x.flower==='Bertambah').length],['Ada buah',vals.filter(x=>x.fruit==='Ada'||x.fruit==='Bertambah').length],['Tanpa hama',vals.filter(x=>x.pest==='Tidak ada').length]];$('#indicatorBars').innerHTML=indicators.map(([k,v])=>`<div class="bar-row"><span>${k}</span><div class="bar-track"><div class="bar-fill" style="width:${v/12*100}%"></div></div><strong>${v}/12</strong></div>`).join('');const day=todayDay();$('#phaseTimeline').innerHTML=phases.map((p,i)=>`<article class="phase-item ${day>=p.from&&day<=p.to?'current':''}"><span class="phase-num">${i+1}</span><div><h3>Hari ${p.from}–${p.to} · ${p.name}</h3><p>${p.target}</p></div></article>`).join('')}
function renderAll(){renderHome();renderSchedule();renderTrees();renderReport()}
function go(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));scrollTo({top:0,behavior:'smooth'});if(view==='jadwal')renderSchedule();if(view==='laporan')renderReport()}
function openCheck(day,tree=1){selectedDay=day;$('#checkDay').textContent=`HARI KE-${day} · ${fmt(dateAt(day)).toUpperCase()}`;$('#treeSelect').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}" ${i+1===tree?'selected':''}>Pohon ${i+1} · Kelompok ${groupFor(i+1)}</option>`).join('');$$('.choice-row button').forEach(b=>b.classList.remove('selected'));$('#actionNote').value='';$('#heightCm').value='';$('#stemCm').value='';$('#moisturePct').value='';const old=state.trees[tree];if(old)fillForm(old);$('#checkDialog').showModal()}
function fillForm(data){Object.entries(data).forEach(([k,v])=>{const b=document.querySelector(`.choice-row[data-name="${k}"] button[data-value="${CSS.escape(String(v))}"]`);if(b)b.classList.add('selected')});$('#heightCm').value=data.heightCm??'';$('#stemCm').value=data.stemCm??'';$('#moisturePct').value=data.moisturePct??'';$('#actionNote').value=data.note||''}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
$('#startCheckBtn').addEventListener('click',()=>openCheck(todayDay()));$('#settingsBtn').addEventListener('click',()=>{$('#startDate').value=state.startDate;$('#settingsDialog').showModal()});
document.addEventListener('click',e=>{const s=e.target.closest('.schedule-item');if(s)openCheck(+s.dataset.day);const t=e.target.closest('[data-tree]');if(t)openCheck(todayDay(),+t.dataset.tree)});
$$('.choice-row button').forEach(b=>b.addEventListener('click',()=>{const row=b.parentElement;row.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}));
$('#treeSelect').addEventListener('change',e=>{$$('.choice-row button').forEach(b=>b.classList.remove('selected'));$('#actionNote').value='';$('#heightCm').value='';$('#stemCm').value='';$('#moisturePct').value='';const old=state.trees[e.target.value];if(old)fillForm(old)});
$('#checkForm').addEventListener('submit',e=>{e.preventDefault();const tree=+$('#treeSelect').value,data={};$$('.choice-row').forEach(row=>{const sel=row.querySelector('.selected');if(sel)data[row.dataset.name]=sel.dataset.value});[['heightCm','#heightCm'],['stemCm','#stemCm'],['moisturePct','#moisturePct']].forEach(([key,selector])=>{const value=$(selector).value;if(value!=='')data[key]=+value});data.note=$('#actionNote').value.trim();data.savedAt=new Date().toISOString();state.trees[tree]=data;state.checks[selectedDay]={...(state.checks[selectedDay]||{}),[tree]:data};save();$('#checkDialog').close();renderAll();toast(`Pemeriksaan Pohon ${tree} tersimpan`)});
$('#settingsForm').addEventListener('submit',e=>{e.preventDefault();state.startDate=$('#startDate').value;save();$('#settingsDialog').close();renderAll();toast('Tanggal awal diperbarui')});
$$('.segmented button').forEach(b=>b.addEventListener('click',()=>{$$('.segmented button').forEach(x=>x.classList.remove('active'));b.classList.add('active');scheduleFilter=b.dataset.filter;renderSchedule()}));
function safe(value){return String(value??'-').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function reportHTML(){const items=schedule(),done=items.filter(x=>x.done).length,pct=Math.round(done/items.length*100),treeRows=Array.from({length:12},(_,i)=>{const n=i+1,t=state.trees[n]||{},status=statusFor(n).label;return `<tr><td>${n}</td><td>${groupFor(n)}</td><td>${safe(t.soil)}</td><td>${safe(t.leaf)}</td><td>${safe(t.shoot)}</td><td>${safe(t.flower)}</td><td>${safe(t.fruit)}</td><td>${safe(t.pest)}</td><td>${safe(t.weed)}</td><td>${safe(status)}</td><td>${safe(t.note)}</td></tr>`}).join(''),history=Object.entries(state.checks).sort((a,b)=>+a[0]-+b[0]).map(([day,trees])=>Object.entries(trees).map(([tree,t])=>`<tr><td>${day}</td><td>${fmt(dateAt(+day))}</td><td>Pohon ${tree}</td><td>${safe(t.soil)}</td><td>${safe(t.leaf)}</td><td>${safe(t.flower)}</td><td>${safe(t.fruit)}</td><td>${safe(t.note)}</td></tr>`).join('')).join('')||'<tr><td colspan="8">Belum ada riwayat pemeriksaan.</td></tr>';return `<!doctype html><html><head><meta charset="utf-8"><title>Laporan Rambutan 365 Hari</title><style>@page{size:A4 landscape;margin:12mm}body{font-family:Arial,sans-serif;color:#18372b;font-size:10px}h1{margin:0 0 4px;font-size:22px}h2{margin:22px 0 8px;font-size:15px}.meta{color:#587066;margin-bottom:14px}.summary{display:flex;gap:12px;margin:15px 0}.box{border:1px solid #bfd0c5;border-radius:8px;padding:10px 14px}.box strong{display:block;font-size:18px;color:#174c35}table{width:100%;border-collapse:collapse;margin-bottom:12px}th,td{border:1px solid #ccd7d0;padding:6px;text-align:left;vertical-align:top}th{background:#174c35;color:white}tr:nth-child(even) td{background:#f1f6f2}.footer{margin-top:18px;color:#718078;font-size:9px}@media print{button{display:none}}</style></head><body><h1>Laporan Pengendalian dan Evaluasi Rambutan</h1><div class="meta">12 Pohon Rambutan Belereng Pendek · Periode 365 Hari · Dicetak ${safe(fmt(new Date(),true))}</div><div class="summary"><div class="box"><strong>${done}/${items.length}</strong>Pemeriksaan selesai</div><div class="box"><strong>${pct}%</strong>Kepatuhan jadwal</div><div class="box"><strong>Hari ke-${todayDay()}</strong>${safe(phaseFor(todayDay()).name)}</div></div><h2>Kondisi terakhir 12 pohon</h2><table><thead><tr><th>Pohon</th><th>Kel.</th><th>Tanah</th><th>Daun</th><th>Tunas</th><th>Bunga</th><th>Buah</th><th>Hama</th><th>Gulma</th><th>Status</th><th>Catatan</th></tr></thead><tbody>${treeRows}</tbody></table><h2>Riwayat pemeriksaan</h2><table><thead><tr><th>Hari</th><th>Tanggal</th><th>Pohon</th><th>Tanah</th><th>Daun</th><th>Bunga</th><th>Buah</th><th>Tindakan/catatan</th></tr></thead><tbody>${history}</tbody></table><div class="footer">Dibuat melalui aplikasi Rambutan Lapangan. Pilih Simpan sebagai PDF pada menu cetak.</div></body></html>`}
$('#downloadReportBtn').addEventListener('click',()=>{const report=window.open('','_blank');if(!report){toast('Izinkan pop-up untuk membuat laporan');return}report.document.open();report.document.write(reportHTML());report.document.close();report.focus();setTimeout(()=>report.print(),500)});
$('#exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cadangan-rambutan-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Cadangan data diunduh')});
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});renderAll();
